# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'labels', 'examples', 'intf', 'classify_image']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% ../app.ipynb 3
learn = load_learner('app/model.pkl')

# %% ../app.ipynb 5
categories = ('Minecraft', 'Real World')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% ../app.ipynb 7
image = gr.Image(shape=(224,224))
labels = gr.Label()
examples = ['samples/minecraft.jpg', 'samples/real-world.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=labels, examples=examples, allow_flagging="never")
intf.launch(inline=False, server_port=8080)